/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedRecentCampaignsRouteImport } from './routes/_authenticated.recent-campaigns'
import { Route as AuthenticatedHowItWorksRouteImport } from './routes/_authenticated.how-it-works'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecentCampaignsRoute =
  AuthenticatedRecentCampaignsRouteImport.update({
    id: '/recent-campaigns',
    path: '/recent-campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHowItWorksRoute = AuthenticatedHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/recent-campaigns': typeof AuthenticatedRecentCampaignsRoute
}
export interface FileRoutesByTo {
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/recent-campaigns': typeof AuthenticatedRecentCampaignsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/_authenticated/recent-campaigns': typeof AuthenticatedRecentCampaignsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/how-it-works' | '/recent-campaigns'
  fileRoutesByTo: FileRoutesByTo
  to: '/how-it-works' | '/recent-campaigns' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/how-it-works'
    | '/_authenticated/recent-campaigns'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recent-campaigns': {
      id: '/_authenticated/recent-campaigns'
      path: '/recent-campaigns'
      fullPath: '/recent-campaigns'
      preLoaderRoute: typeof AuthenticatedRecentCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/how-it-works': {
      id: '/_authenticated/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedHowItWorksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHowItWorksRoute: typeof AuthenticatedHowItWorksRoute
  AuthenticatedRecentCampaignsRoute: typeof AuthenticatedRecentCampaignsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHowItWorksRoute: AuthenticatedHowItWorksRoute,
  AuthenticatedRecentCampaignsRoute: AuthenticatedRecentCampaignsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
